/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.knowarth.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the IndianState service. Represents a row in the &quot;IndianState&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.knowarth.service.model.impl.IndianStateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.knowarth.service.model.impl.IndianStateImpl}.
 * </p>
 *
 * @author shyam.vadera
 * @see IndianState
 * @see com.knowarth.service.model.impl.IndianStateImpl
 * @see com.knowarth.service.model.impl.IndianStateModelImpl
 * @generated
 */
public interface IndianStateModel extends BaseModel<IndianState> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a indian state model instance should use the {@link IndianState} interface instead.
	 */

	/**
	 * Returns the primary key of this indian state.
	 *
	 * @return the primary key of this indian state
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this indian state.
	 *
	 * @param primaryKey the primary key of this indian state
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the state ID of this indian state.
	 *
	 * @return the state ID of this indian state
	 */
	public long getStateId();

	/**
	 * Sets the state ID of this indian state.
	 *
	 * @param stateId the state ID of this indian state
	 */
	public void setStateId(long stateId);

	/**
	 * Returns the state name of this indian state.
	 *
	 * @return the state name of this indian state
	 */
	@AutoEscape
	public String getStateName();

	/**
	 * Sets the state name of this indian state.
	 *
	 * @param stateName the state name of this indian state
	 */
	public void setStateName(String stateName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.knowarth.service.model.IndianState indianState);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.knowarth.service.model.IndianState> toCacheModel();

	@Override
	public com.knowarth.service.model.IndianState toEscapedModel();

	@Override
	public com.knowarth.service.model.IndianState toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}