/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.knowarth.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the patient service. Represents a row in the &quot;PatientDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.knowarth.service.model.impl.patientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.knowarth.service.model.impl.patientImpl}.
 * </p>
 *
 * @author shyam.vadera
 * @see patient
 * @see com.knowarth.service.model.impl.patientImpl
 * @see com.knowarth.service.model.impl.patientModelImpl
 * @generated
 */
public interface patientModel extends BaseModel<patient> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a patient model instance should use the {@link patient} interface instead.
	 */

	/**
	 * Returns the primary key of this patient.
	 *
	 * @return the primary key of this patient
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this patient.
	 *
	 * @param primaryKey the primary key of this patient
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the patient ID of this patient.
	 *
	 * @return the patient ID of this patient
	 */
	public long getPatientId();

	/**
	 * Sets the patient ID of this patient.
	 *
	 * @param patientId the patient ID of this patient
	 */
	public void setPatientId(long patientId);

	/**
	 * Returns the patient name of this patient.
	 *
	 * @return the patient name of this patient
	 */
	@AutoEscape
	public String getPatientName();

	/**
	 * Sets the patient name of this patient.
	 *
	 * @param patientName the patient name of this patient
	 */
	public void setPatientName(String patientName);

	/**
	 * Returns the patient email ID of this patient.
	 *
	 * @return the patient email ID of this patient
	 */
	@AutoEscape
	public String getPatientEmailId();

	/**
	 * Sets the patient email ID of this patient.
	 *
	 * @param patientEmailId the patient email ID of this patient
	 */
	public void setPatientEmailId(String patientEmailId);

	/**
	 * Returns the patient age of this patient.
	 *
	 * @return the patient age of this patient
	 */
	public long getPatientAge();

	/**
	 * Sets the patient age of this patient.
	 *
	 * @param patientAge the patient age of this patient
	 */
	public void setPatientAge(long patientAge);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.knowarth.service.model.patient patient);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.knowarth.service.model.patient> toCacheModel();

	@Override
	public com.knowarth.service.model.patient toEscapedModel();

	@Override
	public com.knowarth.service.model.patient toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}