/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.knowarth.service.service.base;

import com.knowarth.service.model.Employee;
import com.knowarth.service.service.EmployeeService;
import com.knowarth.service.service.persistence.EmployeePersistence;
import com.knowarth.service.service.persistence.IndianStatePersistence;
import com.knowarth.service.service.persistence.patientPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the employee remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.knowarth.service.service.impl.EmployeeServiceImpl}.
 * </p>
 *
 * @author shyam.vadera
 * @see com.knowarth.service.service.impl.EmployeeServiceImpl
 * @see com.knowarth.service.service.EmployeeServiceUtil
 * @generated
 */
public abstract class EmployeeServiceBaseImpl extends BaseServiceImpl
	implements EmployeeService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.knowarth.service.service.EmployeeServiceUtil} to access the employee remote service.
	 */

	/**
	 * Returns the employee local service.
	 *
	 * @return the employee local service
	 */
	public com.knowarth.service.service.EmployeeLocalService getEmployeeLocalService() {
		return employeeLocalService;
	}

	/**
	 * Sets the employee local service.
	 *
	 * @param employeeLocalService the employee local service
	 */
	public void setEmployeeLocalService(
		com.knowarth.service.service.EmployeeLocalService employeeLocalService) {
		this.employeeLocalService = employeeLocalService;
	}

	/**
	 * Returns the employee remote service.
	 *
	 * @return the employee remote service
	 */
	public com.knowarth.service.service.EmployeeService getEmployeeService() {
		return employeeService;
	}

	/**
	 * Sets the employee remote service.
	 *
	 * @param employeeService the employee remote service
	 */
	public void setEmployeeService(
		com.knowarth.service.service.EmployeeService employeeService) {
		this.employeeService = employeeService;
	}

	/**
	 * Returns the employee persistence.
	 *
	 * @return the employee persistence
	 */
	public EmployeePersistence getEmployeePersistence() {
		return employeePersistence;
	}

	/**
	 * Sets the employee persistence.
	 *
	 * @param employeePersistence the employee persistence
	 */
	public void setEmployeePersistence(EmployeePersistence employeePersistence) {
		this.employeePersistence = employeePersistence;
	}

	/**
	 * Returns the indian state local service.
	 *
	 * @return the indian state local service
	 */
	public com.knowarth.service.service.IndianStateLocalService getIndianStateLocalService() {
		return indianStateLocalService;
	}

	/**
	 * Sets the indian state local service.
	 *
	 * @param indianStateLocalService the indian state local service
	 */
	public void setIndianStateLocalService(
		com.knowarth.service.service.IndianStateLocalService indianStateLocalService) {
		this.indianStateLocalService = indianStateLocalService;
	}

	/**
	 * Returns the indian state remote service.
	 *
	 * @return the indian state remote service
	 */
	public com.knowarth.service.service.IndianStateService getIndianStateService() {
		return indianStateService;
	}

	/**
	 * Sets the indian state remote service.
	 *
	 * @param indianStateService the indian state remote service
	 */
	public void setIndianStateService(
		com.knowarth.service.service.IndianStateService indianStateService) {
		this.indianStateService = indianStateService;
	}

	/**
	 * Returns the indian state persistence.
	 *
	 * @return the indian state persistence
	 */
	public IndianStatePersistence getIndianStatePersistence() {
		return indianStatePersistence;
	}

	/**
	 * Sets the indian state persistence.
	 *
	 * @param indianStatePersistence the indian state persistence
	 */
	public void setIndianStatePersistence(
		IndianStatePersistence indianStatePersistence) {
		this.indianStatePersistence = indianStatePersistence;
	}

	/**
	 * Returns the patient local service.
	 *
	 * @return the patient local service
	 */
	public com.knowarth.service.service.patientLocalService getpatientLocalService() {
		return patientLocalService;
	}

	/**
	 * Sets the patient local service.
	 *
	 * @param patientLocalService the patient local service
	 */
	public void setpatientLocalService(
		com.knowarth.service.service.patientLocalService patientLocalService) {
		this.patientLocalService = patientLocalService;
	}

	/**
	 * Returns the patient remote service.
	 *
	 * @return the patient remote service
	 */
	public com.knowarth.service.service.patientService getpatientService() {
		return patientService;
	}

	/**
	 * Sets the patient remote service.
	 *
	 * @param patientService the patient remote service
	 */
	public void setpatientService(
		com.knowarth.service.service.patientService patientService) {
		this.patientService = patientService;
	}

	/**
	 * Returns the patient persistence.
	 *
	 * @return the patient persistence
	 */
	public patientPersistence getpatientPersistence() {
		return patientPersistence;
	}

	/**
	 * Sets the patient persistence.
	 *
	 * @param patientPersistence the patient persistence
	 */
	public void setpatientPersistence(patientPersistence patientPersistence) {
		this.patientPersistence = patientPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		Class<?> clazz = getClass();

		_classLoader = clazz.getClassLoader();
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	@Override
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	@Override
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	@Override
	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		Thread currentThread = Thread.currentThread();

		ClassLoader contextClassLoader = currentThread.getContextClassLoader();

		if (contextClassLoader != _classLoader) {
			currentThread.setContextClassLoader(_classLoader);
		}

		try {
			return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
		}
		finally {
			if (contextClassLoader != _classLoader) {
				currentThread.setContextClassLoader(contextClassLoader);
			}
		}
	}

	protected Class<?> getModelClass() {
		return Employee.class;
	}

	protected String getModelClassName() {
		return Employee.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = employeePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.knowarth.service.service.EmployeeLocalService.class)
	protected com.knowarth.service.service.EmployeeLocalService employeeLocalService;
	@BeanReference(type = com.knowarth.service.service.EmployeeService.class)
	protected com.knowarth.service.service.EmployeeService employeeService;
	@BeanReference(type = EmployeePersistence.class)
	protected EmployeePersistence employeePersistence;
	@BeanReference(type = com.knowarth.service.service.IndianStateLocalService.class)
	protected com.knowarth.service.service.IndianStateLocalService indianStateLocalService;
	@BeanReference(type = com.knowarth.service.service.IndianStateService.class)
	protected com.knowarth.service.service.IndianStateService indianStateService;
	@BeanReference(type = IndianStatePersistence.class)
	protected IndianStatePersistence indianStatePersistence;
	@BeanReference(type = com.knowarth.service.service.patientLocalService.class)
	protected com.knowarth.service.service.patientLocalService patientLocalService;
	@BeanReference(type = com.knowarth.service.service.patientService.class)
	protected com.knowarth.service.service.patientService patientService;
	@BeanReference(type = patientPersistence.class)
	protected patientPersistence patientPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
	protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
	@BeanReference(type = com.liferay.portal.service.UserLocalService.class)
	protected com.liferay.portal.service.UserLocalService userLocalService;
	@BeanReference(type = com.liferay.portal.service.UserService.class)
	protected com.liferay.portal.service.UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ClassLoader _classLoader;
	private EmployeeServiceClpInvoker _clpInvoker = new EmployeeServiceClpInvoker();
}